---
title: "commandcenterTemplate"
output: html_document
params:
  pathToRuns: ".."
  hrs: 24
  outputFolders: "outputs"
---

<!-- This is based on the template here: "https://raw.githubusercontent.com/DataStrategist/automateMe/master/ccDrafft.Rmd" -->

## Overall Status:
```{r setup, results='hide', message=FALSE, warning=FALSE, echo=FALSE}
print(Sys.time())
library(tidyverse, verbose = FALSE, quietly = TRUE)
options(scipen = 999)
```

```{r overall, warning=FALSE, echo=FALSE}
text <- list.files(params$pathToRuns, pattern = ".log",
                     full.names = TRUE, recursive = TRUE) %>% set_names %>% 
    map(file) %>% map(readLines) %>% enframe

script_errors <- text %>% unnest(value) %>% filter(grepl(" [eE]rror", value)) %>% 
  group_by(name) %>% unique %>% rename(error = value)

if (nrow(script_errors) != 0) {
  script_errors %>% gt::gt()
} else {
  tibble(errors = "No errors! 🙂") %>% gt::gt()
}
```

## Last runs:
```{r lastRuns, warning=FALSE, echo=FALSE}
text <- list.files(params$pathToRuns, pattern = "timeRun",
                     full.names = TRUE, recursive = TRUE) %>%
    map(file) %>% map(readLines)

## first test if the latest value is in errorstate.
cront_itself_in_errorstate <- text %>% map(tail, 1) %>% unlist %>% discard(~grepl("^XXX", .x))

if (length(cront_itself_in_errorstate) != 0) {
  gt::gt(cront_itself_in_errorstate %>% as.data.frame, caption = "Error")
} else{
  text <- text %>% unlist %>% keep(~grepl("^XXX", .x))
  ## Into df
  df <-
    tibble(script = gsub(" [0-9]{10}.+", "", text),
           sdt = text %>%
             gsub(".+([0-9]{10}).+", "\\1", .) %>% as.numeric %>%
             as.POSIXct(., origin = "1970-01-01",tz = "GMT"),
           runtime = gsub(".+ ", "", text) %>%
             as.numeric,
           name = gsub(".+/(.+).sh.+", "\\1", text) %>%
             gsub("XXX ", "", .) %>%
             gsub(" .+", "", .)) %>%
    ## Grab only the last {hrs} hours of stuff:
    filter(sdt > Sys.time() - 3600 * params$hrs) %>%
    select(name, sdt, runtime)
  
  df %>% ggplot(aes(x=sdt, y = runtime, color = name)) + geom_point() + geom_line()
  
}

```
## latest outputs:
```{r warning=FALSE, echo=FALSE}
# browser()
text <- list.dirs(path = params$pathToRuns) %>% grep(pattern = paste0(params$outputFolders, "$"), value = TRUE)

text <- text %>% set_names %>% map(list.files, full.names = TRUE) %>% enframe %>% unnest(value)

runs <- text$value %>% map(file.info) %>% map(rownames_to_column) %>% bind_rows %>% 
  mutate(howLong = Sys.time()-mtime)

text <- left_join(text, runs, by = c("value" = "rowname"))

text %>% 
  group_by(name) %>% summarize(max = max(howLong), min = min(howLong), mean = mean(howLong)) %>% 
  mutate_if(lubridate::is.difftime, round)
```

